FROM php:7.4-apache

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd mysqli bcmath

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY app/ /var/www/html/

#RUN cp /var/www/html/config.local.php /var/www/html/config.php
#RUN cp /var/www/html/admin/config.local.php /var/www/html/admin/config.php

RUN chmod 777 -R /var/www/html/system/storage/logs/
RUN chmod 777 -R /var/www/html/system/storage/cache/
RUN chmod 777 -R /var/www/html/image/cache/

WORKDIR /var/www/html/

EXPOSE 80 443