version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-local
    container_name: php-app
    tty: true
    ports:
      - 8081:80
    volumes:
      - ./app/:/var/www/html/
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: draculartes-dev
    volumes:
      - ./mysql/dump:/var/tmp
#      - ./mysql/initial:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
